"""create enrolled_devices

Revision ID: 5772c170cb84
Revises: 
Create Date: 2026-09-07 17:17:34.079407

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5772c170cb84'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('enrolled_devices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('device_id', sa.String(length=128), nullable=False),
    sa.Column('site_id', sa.String(length=128), nullable=False),
    sa.Column('credential_hash', sa.String(length=512), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'REVOKED', name='device_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_enrolled_devices_device_id'), 'enrolled_devices', ['device_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_enrolled_devices_device_id'), table_name='enrolled_devices')
    op.drop_table('enrolled_devices')
    # ### end Alembic commands ###
    sa.Enum(name='device_status').drop(op.get_bind(), checkfirst=True)
