-- Orion MVP — purchases (orders)
-- One row per completed/attempted purchase, owned by a single auth user.
--
-- Purchases are created ONLY by a secure backend process (service_role, which
-- bypasses RLS) AFTER payment confirmation. Authenticated end users can read
-- their own purchases but can never insert, update, or delete them directly —
-- there is intentionally no INSERT/UPDATE/DELETE policy, so RLS default-denies
-- those actions for the `authenticated` role.
--
-- Line items (the individual RFID-tagged products in an order) live in a future
-- `public.purchase_items` table that references purchases(id); this table is the
-- stable order "header" that scales to millions of rows.

-- =============================================================================
-- Enum for order lifecycle status
-- =============================================================================
create type public.purchase_status as enum (
  'pending',      -- created, awaiting payment confirmation
  'processing',   -- payment authorized, order being fulfilled
  'completed',    -- paid and fulfilled
  'failed',       -- payment or fulfilment failed
  'cancelled',    -- cancelled before completion
  'refunded'      -- previously completed, money returned
);

-- =============================================================================
-- Table
-- =============================================================================
create table public.purchases (
  id                uuid                    primary key default gen_random_uuid(),

  -- Human-friendly, customer-facing identifier (e.g. on receipts). Generated by
  -- the backend; unique across all purchases.
  order_number      text                    not null,

  -- Owner. Purchases are removed if the user is deleted.
  user_id           uuid                    not null references auth.users (id)       on delete cascade,

  -- Which saved card paid for this. Nullable so historical purchases survive the
  -- card being deleted (SET NULL rather than CASCADE keeps the order record).
  payment_method_id uuid                    references public.payment_methods (id)    on delete set null,

  status            public.purchase_status  not null default 'pending',

  -- Money. numeric(12,2) holds up to ~10 billion in the minor-unit-free form and
  -- avoids floating-point rounding. currency is an ISO-4217 3-letter code.
  subtotal          numeric(12,2)           not null,
  tax               numeric(12,2)           not null default 0,
  total             numeric(12,2)           not null,
  currency          char(3)                 not null default 'USD',

  -- When the purchase actually happened (set by the backend on confirmation).
  purchased_at      timestamptz             not null default now(),
  created_at        timestamptz             not null default now(),
  updated_at        timestamptz             not null default now(),

  -- One customer-facing order number, globally unique.
  constraint uq_purchases_order_number unique (order_number),

  -- Shape / sanity guards.
  constraint order_number_not_blank check (length(btrim(order_number)) > 0),
  constraint currency_format        check (currency ~ '^[A-Z]{3}$'),
  constraint subtotal_non_negative  check (subtotal >= 0),
  constraint tax_non_negative       check (tax >= 0),
  constraint total_non_negative     check (total >= 0)
);

comment on table  public.purchases is 'Order headers. Created only by a trusted backend after payment confirmation; users have read-only access to their own rows.';
comment on column public.purchases.order_number is 'Unique customer-facing order identifier (receipts, support). Generated by the backend.';
comment on column public.purchases.payment_method_id is 'Card used, if any. SET NULL on card deletion so the historical order is preserved.';
comment on column public.purchases.status is 'Order lifecycle state (purchase_status enum).';
comment on column public.purchases.purchased_at is 'Business time the purchase was confirmed (distinct from created_at, the row-insert time).';

-- =============================================================================
-- Keep updated_at fresh (reuses the function created in the profiles migration)
-- =============================================================================
create trigger trg_purchases_set_updated_at
  before update on public.purchases
  for each row
  execute function public.set_updated_at();

-- =============================================================================
-- Row Level Security — read-only, owner-only
-- =============================================================================
alter table public.purchases enable row level security;

-- Users may read only their own purchases.
create policy "select_own_purchases"
  on public.purchases
  for select
  to authenticated
  using (auth.uid() = user_id);

-- NO insert/update/delete policies by design: end users cannot write purchases.
-- The backend uses the service_role key, which bypasses RLS entirely.

-- =============================================================================
-- Indexes
-- =============================================================================
-- Most common query: list a user's purchases newest-first (paginated history).
create index idx_purchases_user_purchased_at
  on public.purchases (user_id, purchased_at desc);

-- Supports backend lookups / dashboards that filter a user's orders by status.
create index idx_purchases_user_status
  on public.purchases (user_id, status);

-- Foreign-key helper so deleting a payment_method (SET NULL) doesn't scan.
create index idx_purchases_payment_method_id
  on public.purchases (payment_method_id)
  where payment_method_id is not null;

-- Note: uq_purchases_order_number already creates a unique index on order_number,
-- covering direct order-number lookups.
